### ISSUE TITLE
change username and password to function args

### ISSUE THREAD

**Issue by kenneth-reitz** [heaptracetechnology/microservice-ssh#2]
let's make private_key an environment variable (as it is), and make all the others function arguments.

This will allow people to communicate between various hosts easily.

**Comment by heaptracetechnology** [comment]
Change username and password as function args updated in code and yml file and committed.

**Comment by kenneth-reitz** [comment]
host should be an argument too

**Comment by kenneth-reitz** [comment]
sorry for any confusion
